version: '3'

services:
  db: 
    build: 
      context: ./MySQL
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    container_name: go_app_db
    ports:
      - "3300:3306"
    tty: true
  app:
    build:
      context: ./Go
    restart: always
    container_name: go_app
    ports: 
      - "8080:8080"
    tty: true
    depends_on:
      - db